import type { CompassDirection } from "./lightning/bearing.ts";
import type { RiskLevel } from "./weather.ts";

export type Locale = "tr" | "en";
export const LOCALE_STORAGE_KEY = "lightning-nearby:locale";
export const DEFAULT_LOCALE: Locale = "tr";

export function parseLocale(value: unknown): Locale { return value === "en" ? "en" : "tr"; }
export function readStoredLocale(storage: Pick<Storage, "getItem">): Locale {
  try { return parseLocale(storage.getItem(LOCALE_STORAGE_KEY)); } catch { return DEFAULT_LOCALE; }
}
export function saveLocale(storage: Pick<Storage, "setItem">, locale: Locale): void {
  try { storage.setItem(LOCALE_STORAGE_KEY, locale); } catch { /* Language switching still works for this page. */ }
}
export const intlLocale = (locale: Locale) => locale === "tr" ? "tr-TR" : "en-GB";
export function formatDayLabel(epoch: number, timezone: string, locale: Locale): string {
  return new Intl.DateTimeFormat(intlLocale(locale), { timeZone: timezone, weekday: "short", day: "numeric", month: "short" }).format(epoch * 1000);
}
export function formatClock(ms: number, timezone: string, locale: Locale): string {
  return new Intl.DateTimeFormat(intlLocale(locale), { timeZone: timezone, hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(ms);
}
export function formatDistance(distance: number, locale: Locale): string {
  return new Intl.NumberFormat(intlLocale(locale), { minimumFractionDigits: 1, maximumFractionDigits: 1 }).format(distance);
}

const en = {
  edition: "LOCAL OUTLOOK", editionPeriod: "24H", location: "LOCATION", choosePoint: "Choose a point", cancel: "Cancel",
  searchPlace: "Search place", pickOnMap: "Pick on map", searchPlaceholder: "City, town, place, or coordinates", search: "Search", searching: "Searching…", searchingPlaces: "Searching places…",
  showMore: "Show more", mapInstruction: "Tap the map to place one marker. Pan and zoom to refine the point.", mapAttribution: "Map tiles and place labels © OpenStreetMap contributors.",
  useThisLocation: "Use this location", findingPlace: "Finding place…", savingLocation: "Saving location…", mapPrivacy: "Confirming this point may send its coordinates to OpenStreetMap Nominatim to find a place label.",
  openingForecast: "Opening your local forecast…", brandHome: "Lightning Nearby home", welcomeEyebrow: "LOCAL LIGHTNING OUTLOOK", welcomeTitle: "See the chance of lightning near you.",
  welcomeCopy: "Choose a location to check the next 24 hours of thunderstorm conditions and current lightning activity nearby.",
  useMyLocation: "Use my location", findingLocation: "Finding location…", openPicker: "Search for a place or choose on map", permissionNote: "Your location is accessed only when you allow it. Your selected location is saved on this device.",
  disclaimerShort: "Forecast guidance only. This is not an official weather warning.", monitoredLocation: "MONITORED LOCATION", refreshForecast: "Refresh forecast", refreshing: "Refreshing…", useCurrentLocation: "Use current location", locating: "Locating…", searchMap: "Search / map",
  gettingForecast: "Getting the latest forecast…", forecastUnavailable: "Forecast unavailable", forecastError: "Open‑Meteo could not provide enough current forecast data. Check your connection and try again. No old forecast is shown as current.", tryAgain: "Try again",
  next24hOutlook: "NEXT 24H OUTLOOK", strongestWindow: "Strongest window", hoursAhead: "THE HOURS AHEAD", hourlyOutlook: "Hourly outlook", localTime: "Local time", timelineInstruction: "Tap an hour to see its forecast values.", timelineScroll: "Hourly thunderstorm outlook. Scroll horizontally to see more hours.",
  riskLegend: "Risk level legend", derivedOutlook: "Derived outlook", selectedHour: "SELECTED HOUR", forecastValues: "Open‑Meteo forecast values", weather: "Weather", thunderstormProbability: "Thunderstorm probability", providerValue: "provider value", nearbyModelSupport: "Nearby model support", present: "Present", precipitationChance: "Precipitation chance",
  insufficientHour: "There is not enough forecast data to assess this hour.", contradictoryForecast: "The weather forecast indicates a thunderstorm here, while the provider's separate probability is low. Forecast indicators can differ.", classificationNote: "Low / Elevated / High is a qualitative forecast signal, not a probability or official warning. Only the provider value above, when shown, is a thunderstorm probability.",
  forecastUpdated: "Forecast updated {time} local time", disclaimerLead: "Forecast guidance, not an official warning.", disclaimerBody: "Forecasts can change and may miss local conditions. Follow your local meteorological and emergency authorities for safety advice.", weatherBy: "Weather data by", poweredBy: "Powered by", privacyFooter: "Saved here · device/map coordinates sent to OpenStreetMap for place labels", developerPages: "Developer pages", forecastDebug: "Forecast debug", lightningDebug: "Lightning debug",
  locationUnsupported: "Location isn’t available in this browser. Try again in a browser that supports location.", locationDenied: "Location access was declined. Allow it in your browser or device settings, then try again.", locationUnavailable: "Your device couldn’t determine a location. Check location services and try again.", locationTimeout: "The location request took too long. Check your signal and try again.", locationFailed: "We couldn’t get your location. Check your device settings and try again.", saveLocationFailed: "This browser couldn’t save your location on this device. Check its storage settings and try again.", saveSelectionFailed: "This browser couldn’t save the selected location on this device. Check its storage settings and try again.",
  invalidCoordinates: "Enter valid coordinates: latitude from −90 to 90, longitude from −180 to 180.", queryTooShort: "Enter at least {count} characters to search.", searchUnavailable: "Place search is unavailable right now. Check your connection and try again.", noPlaces: "No matching places found. Try a nearby town or a broader search.", selectedCoordinates: "Selected coordinates",
  contextualMatch: "No exact combined match; showing places that match the supplied location context.", noContextualMatch: "No exact combined match found. Try a broader search or choose a point on the map.",
  mapLoading: "Loading map…", mapError: "The map could not be loaded. You can still search for a place.", mapLabel: "Choose a location on the map",
  today: "TODAY", nowTemp: "Now {temp}°C", highTemp: "high {temp}°C", lowTemp: "low {temp}°C",
  clearSkies: "Clear skies", mostlyClear: "Mostly clear skies", partlyCloudy: "Partly cloudy skies", overcast: "Overcast skies", fog: "Fog", drizzle: "Drizzle", rain: "Rain", rainShowers: "Rain showers", snow: "Snow", thunderstorms: "Thunderstorms",
  precipLikely: "Precipitation is likely today.", precipPossible: "Precipitation is possible today.", precipLittle: "Little or no precipitation is expected today.",
  low: "Low", elevated: "Elevated", high: "High", nearbyActivity: "Nearby activity", forecastLow: "Low signal in next 24h", forecastElevated: "Elevated signal in next 24h", forecastHigh: "High signal in next 24h",
  noElevatedSignal: "No elevated thunderstorm signal in the available forecast hours. Local storms remain possible.", highSummary: "Thunderstorm conditions are indicated in the forecast. Strongest period: {period}.", elevatedSummary: "Thunderstorm activity is plausible near this location around {period}.",
  currentPicture: "CURRENT PICTURE", liveLightning: "LIVE LIGHTNING", checkedTime: "Checked {time} local time", checkingNearby: "Checking nearby lightning…", requestingObservation: "Requesting the latest lightning observation for this location.", checkCurrent: "Check current lightning nearby", runLiveCheck: "Run a live check to see whether lightning is currently detected nearby.", liveUnavailable: "Live lightning unavailable", liveUnavailableBody: "The current observation could not be completed. Try again when you’re ready.", currentUnavailable: "Current lightning unavailable", lightningNearby: "Lightning activity nearby", closestActivity: "Closest activity:", nearestKmDirection: "{distance} km {direction}", nearestKm: "{distance} km", ageMinutes: "{age} min ago", noCurrentActivity: "No current lightning activity detected within 40 km", checking: "Checking…", refreshLive: "Refresh live activity", checkLive: "Check live activity", forecastContext: "Next 24 hour forecast context", manualNote: "Live check · refresh for a new observation",
  recentUnavailable: "Activity was also detected within 50 km during the last 30 minutes, but current nearby activity is unavailable.", recentClear: "Activity was also detected within 50 km during the last 30 minutes.", noRecent: "No recent lightning activity was reported within 50 km in the last 30 minutes.", recentActive: "Activity also detected within 50 km during the last 30 minutes.", activityNearby: "Lightning activity detected nearby.", eventOne: "{count} recent lightning event within {radius} km · last 5 min", eventMany: "{count} recent lightning events within {radius} km · last 5 min",
  scale: "Scale {distance} km", scaleAccessible: "Scale {distance} kilometres.", proximityClosest: "Closest lightning activity is {distance} kilometres {direction}.", proximityClear: "No current lightning activity detected within 40 kilometres.", noCurrentShort: "no current activity", closestShort: "closest activity {distance} km {direction}", schematic: "schematic proximity, not a map", schematicAccessible: "Schematic proximity, not a map.", northInitial: "N",
  north: "north", northeast: "northeast", east: "east", southeast: "southeast", south: "south", southwest: "southwest", west: "west", northwest: "northwest",
  weatherUnavailable: "Weather code unavailable", thunderstormSignal: "Thunderstorm signal", noRain: "No rain indicated", wmoCode: "WMO weather code {code}", signalUnavailable: "signal unavailable", hourRisk: "{risk} thunderstorm signal",
} as const;

const tr: Record<keyof typeof en, string> = {
  edition: "YEREL GÖRÜNÜM", editionPeriod: "24 SA", location: "KONUM", choosePoint: "Bir konum seçin", cancel: "Vazgeç",
  searchPlace: "Yer ara", pickOnMap: "Haritadan seç", searchPlaceholder: "Şehir, ilçe, yer veya koordinat", search: "Ara", searching: "Aranıyor…", searchingPlaces: "Yerler aranıyor…",
  showMore: "Daha fazla göster", mapInstruction: "Bir nokta seçmek için haritaya dokunun. Haritayı kaydırıp yakınlaştırabilirsiniz.", mapAttribution: "Harita ve yer adları © OpenStreetMap katılımcıları.",
  useThisLocation: "Bu konumu kullan", findingPlace: "Yer adı bulunuyor…", savingLocation: "Konum kaydediliyor…", mapPrivacy: "Bu noktayı onayladığınızda yer adını bulmak için koordinatlar OpenStreetMap Nominatim'e gönderilebilir.",
  openingForecast: "Yerel tahmin açılıyor…", brandHome: "Lightning Nearby ana sayfa", welcomeEyebrow: "YEREL YILDIRIM GÖRÜNÜMÜ", welcomeTitle: "Yakınınızda yıldırım ihtimalini görün.",
  welcomeCopy: "Bir konum seçin; önümüzdeki 24 saatin fırtına görünümünü ve yakın çevredeki güncel yıldırım aktivitesini kontrol edin.",
  useMyLocation: "Konumumu kullan", findingLocation: "Konum bulunuyor…", openPicker: "Yer arayın veya haritadan seçin", permissionNote: "Konumunuza yalnızca siz izin verdiğinizde erişilir. Seçtiğiniz konum bu cihazda saklanır.",
  disclaimerShort: "Tahmin amaçlıdır, resmi bir uyarı değildir.", monitoredLocation: "İZLENEN KONUM", refreshForecast: "Tahmini yenile", refreshing: "Yenileniyor…", useCurrentLocation: "Şu anki konumumu kullan", locating: "Konum bulunuyor…", searchMap: "Ara / harita",
  gettingForecast: "Güncel tahmin alınıyor…", forecastUnavailable: "Tahmin alınamadı", forecastError: "Open‑Meteo yeterli güncel tahmin verisi sağlayamadı. Bağlantınızı kontrol edip yeniden deneyin. Eski tahmin güncel olarak gösterilmez.", tryAgain: "Yeniden dene",
  next24hOutlook: "ÖNÜMÜZDEKİ 24 SAAT", strongestWindow: "En güçlü dönem", hoursAhead: "ÖNÜMÜZDEKİ SAATLER", hourlyOutlook: "Saatlik görünüm", localTime: "Yerel saat", timelineInstruction: "Ayrıntıları görmek için bir saate dokunun.", timelineScroll: "Saatlik fırtına görünümü. Diğer saatler için yatay kaydırın.",
  riskLegend: "Risk düzeyleri", derivedOutlook: "Tahmini görünüm", selectedHour: "SEÇİLEN SAAT", forecastValues: "Open‑Meteo tahmin değerleri", weather: "Hava durumu", thunderstormProbability: "Gök gürültülü fırtına olasılığı", providerValue: "sağlayıcı verisi", nearbyModelSupport: "Yakın çevre model desteği", present: "Var", precipitationChance: "Yağış olasılığı",
  insufficientHour: "Bu saat için yeterli tahmin verisi yok.", contradictoryForecast: "Tahmin burada gök gürültülü fırtınaya işaret ediyor, ancak sağlayıcının ayrı olasılık değeri düşük. Göstergeler farklı sonuçlar verebilir.", classificationNote: "Düşük / Artmış / Yüksek nitel bir risk değerlendirmesidir; olasılık veya resmi uyarı değildir. Yukarıdaki sağlayıcı değeri, gösteriliyorsa gök gürültülü fırtına olasılığıdır.",
  forecastUpdated: "Tahmin güncellendi: {time} (yerel saat)", disclaimerLead: "Tahmin amaçlıdır, resmi bir uyarı değildir.", disclaimerBody: "Tahminler değişebilir ve yerel koşulları gözden kaçırabilir. Güvenliğiniz için yerel meteoroloji ve acil durum yetkililerinin duyurularını izleyin.", weatherBy: "Hava durumu verileri:", poweredBy: "Sağlayıcı:", privacyFooter: "Konum burada saklanır · cihaz/harita koordinatları yer adları için OpenStreetMap'e gönderilir", developerPages: "Geliştirici sayfaları", forecastDebug: "Tahmin hata ayıklama", lightningDebug: "Yıldırım hata ayıklama",
  locationUnsupported: "Bu tarayıcı konumunuzu alamıyor. Konum desteği olan bir tarayıcıda yeniden deneyin.", locationDenied: "Konum izni verilmedi. Tarayıcı veya cihaz ayarlarından izin verip yeniden deneyin.", locationUnavailable: "Cihazınız konum belirleyemedi. Konum hizmetlerini kontrol edip yeniden deneyin.", locationTimeout: "Konum isteği zaman aşımına uğradı. Bağlantınızı kontrol edip yeniden deneyin.", locationFailed: "Konumunuz alınamadı. Cihaz ayarlarını kontrol edip yeniden deneyin.", saveLocationFailed: "Bu tarayıcı konumunuzu cihazda kaydedemedi. Depolama ayarlarını kontrol edip yeniden deneyin.", saveSelectionFailed: "Seçilen konum bu cihazda kaydedilemedi. Depolama ayarlarını kontrol edip yeniden deneyin.",
  invalidCoordinates: "Geçerli koordinatlar girin: enlem −90 ile 90, boylam −180 ile 180 arasında olmalı.", queryTooShort: "Aramak için en az {count} karakter girin.", searchUnavailable: "Yer araması şu anda kullanılamıyor. Bağlantınızı kontrol edip yeniden deneyin.", noPlaces: "Eşleşen yer bulunamadı. Daha geniş bir alanı arayın veya haritadan seçin.", selectedCoordinates: "Seçilen koordinatlar",
  contextualMatch: "Tam birleşik eşleşme yok; verilen konum bağlamına uyan yerler gösteriliyor.", noContextualMatch: "Tam birleşik eşleşme bulunamadı. Daha geniş arayın veya haritadan bir nokta seçin.",
  mapLoading: "Harita yükleniyor…", mapError: "Harita yüklenemedi. Yer aramayı kullanabilirsiniz.", mapLabel: "Haritadan konum seçin",
  today: "BUGÜN", nowTemp: "Şu an {temp}°C", highTemp: "en yüksek {temp}°C", lowTemp: "en düşük {temp}°C",
  clearSkies: "Açık", mostlyClear: "Çoğunlukla açık", partlyCloudy: "Parçalı bulutlu", overcast: "Kapalı", fog: "Sisli", drizzle: "Çisenti", rain: "Yağmurlu", rainShowers: "Sağanak yağışlı", snow: "Karlı", thunderstorms: "Gök gürültülü fırtına",
  precipLikely: "Bugün yağış bekleniyor.", precipPossible: "Bugün yağış ihtimali var.", precipLittle: "Bugün kayda değer yağış beklenmiyor.",
  low: "Düşük", elevated: "Artmış", high: "Yüksek", nearbyActivity: "Yakında aktivite", forecastLow: "Önümüzdeki 24 saatte düşük risk", forecastElevated: "Önümüzdeki 24 saatte artmış risk", forecastHigh: "Önümüzdeki 24 saatte yüksek risk",
  noElevatedSignal: "Tahmin saatlerinde artmış fırtına riski görünmüyor. Yerel fırtınalar yine de oluşabilir.", highSummary: "Tahmin gök gürültülü fırtınaya işaret ediyor. En güçlü dönem: {period}.", elevatedSummary: "{period} civarında gök gürültülü fırtına olasılığı bulunuyor.",
  currentPicture: "GÜNCEL DURUM", liveLightning: "CANLI YILDIRIM DURUMU", checkedTime: "{time} yerel saatte kontrol edildi", checkingNearby: "Yakındaki yıldırımlar kontrol ediliyor…", requestingObservation: "Bu konum için güncel yıldırım verisi alınıyor.", checkCurrent: "Yakındaki yıldırım durumunu kontrol edin", runLiveCheck: "Yakında yıldırım olup olmadığını görmek için canlı durumu kontrol edin.", liveUnavailable: "Canlı yıldırım verisi alınamadı", liveUnavailableBody: "Güncel kontrol tamamlanamadı. Hazır olduğunuzda yeniden deneyin.", currentUnavailable: "Güncel yıldırım verisi alınamadı", lightningNearby: "Yakında yıldırım aktivitesi var", closestActivity: "En yakın aktivite:", nearestKmDirection: "{distance} km {direction} yönünde", nearestKm: "{distance} km", ageMinutes: "{age} dk önce", noCurrentActivity: "40 km içinde güncel yıldırım aktivitesi tespit edilmedi", checking: "Kontrol ediliyor…", refreshLive: "Canlı durumu yenile", checkLive: "Canlı durumu kontrol et", forecastContext: "Önümüzdeki 24 saatin tahmini", manualNote: "Canlı kontrol · yeni gözlem için yenileyin",
  recentUnavailable: "Son 30 dakikada 50 km içinde de aktivite tespit edildi, ancak güncel yakın çevre verisi alınamadı.", recentClear: "Son 30 dakikada 50 km içinde de aktivite tespit edildi.", noRecent: "Son 30 dakikada 50 km içinde yakın yıldırım aktivitesi bildirilmedi.", recentActive: "Son 30 dakikada 50 km içinde de aktivite tespit edildi.", activityNearby: "Yakında yıldırım aktivitesi tespit edildi.", eventOne: "Son 5 dakikada {radius} km içinde {count} yıldırım olayı", eventMany: "Son 5 dakikada {radius} km içinde {count} yıldırım olayı",
  scale: "Ölçek {distance} km", scaleAccessible: "Ölçek {distance} kilometre.", proximityClosest: "En yakın yıldırım aktivitesi {direction} yönünde {distance} kilometre uzaklıkta.", proximityClear: "40 kilometre içinde güncel yıldırım aktivitesi tespit edilmedi.", noCurrentShort: "güncel aktivite yok", closestShort: "en yakın aktivite {distance} km {direction} yönünde", schematic: "şematik yakınlık görünümü · harita değildir", schematicAccessible: "Şematik yakınlık görünümü, harita değildir.", northInitial: "K",
  north: "kuzey", northeast: "kuzeydoğu", east: "doğu", southeast: "güneydoğu", south: "güney", southwest: "güneybatı", west: "batı", northwest: "kuzeybatı",
  weatherUnavailable: "Hava durumu verisi yok", thunderstormSignal: "Gök gürültülü fırtına işareti", noRain: "Yağış beklenmiyor", wmoCode: "WMO hava durumu kodu {code}", signalUnavailable: "risk bilgisi yok", hourRisk: "{risk} fırtına riski",
};

const messages: Record<Locale, Record<keyof typeof en, string>> = { en, tr };
export type MessageKey = keyof typeof en;
export function t(locale: Locale, key: MessageKey, params: Record<string, string | number> = {}): string {
  return messages[locale][key].replace(/\{(\w+)\}/g, (match, name: string) => name in params ? String(params[name]) : match);
}
export function riskLabel(locale: Locale, risk: RiskLevel): string { return t(locale, risk); }
export function forecastHeadline(locale: Locale, risk: RiskLevel): string {
  return t(locale, risk === "high" ? "forecastHigh" : risk === "elevated" ? "forecastElevated" : "forecastLow");
}
const directionKeys: Record<CompassDirection, MessageKey> = { N: "north", NE: "northeast", E: "east", SE: "southeast", S: "south", SW: "southwest", W: "west", NW: "northwest" };
export function directionLabel(locale: Locale, direction: CompassDirection): string { return t(locale, directionKeys[direction]); }
