name: Diagnostic Fly Organization
run-name: Diagnostic Fly Organization

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  org:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@ed8efb33836e8b2096c7fd3ba1c8afe303ebbff1

      - name: Validate Fly CLI
        run: flyctl version

      - name: List accessible Fly organizations
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          set -euo pipefail
          flyctl orgs list
